### ISSUE TITLE
handler + model updates after working on merchant ui

### ISSUE THREAD

**Issue by littlejohntj** [solana-labs/solana-payments-app#62]
So Harsha brought some things to my attention after working on merchant-ui that he feels would improve the ergonomics of the project. 

- covert some specific string groups to enums 
- Transactions on the merchant-ui should be named Payments and the word "transactions" should be reserved to on chain transactions
- Having dates for refund request, refund fulfillment, payment request, payment fulfillment, transaction created, transaction completed
- Change the current amounts to the amount that is being refunded and then in the response for refunds, query the payment record and include the total
- Add a new read-data handler to follow the status of a single refund record.

**Comment by harshasomisetty** [comment]
Think it'd be worth also renaming the id's in each model to things like

- [merchantId instead of ](https://github.com/solana-labs/solana-payments-app/blob/36b6a56b902d212fcb497956804d0edd908ba12a/apps/backend-serverless/prisma/schema.prisma#L16)
- [paymentId](https://github.com/solana-labs/solana-payments-app/blob/36b6a56b902d212fcb497956804d0edd908ba12a/apps/backend-serverless/prisma/schema.prisma#L31)
- same thing for refund
- same thing for transaction

that way reusing id won't get confusing. trade off is queries won't be reusable but safety would increase

**Comment by harshasomisetty** [comment]
specific Enum-like strings for refund status, following this structure

`export enum RefundStatus {
    AwaitingAction = 'AwaitingAction',
    RefundApproved = 'RefundApproved',
    RefundDenied = 'RefundDenied',
}`

**Comment by harshasomisetty** [comment]
missing a person/wallet to refund to. should probably add a field in the refund model and return that data in refund-data handler
